# Generated by Django 3.2.5 on 2021-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
