# Generated by Django 3.2.5 on 2021-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_amount_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
